api/urls.py
from django.urls import path, include
from api.models import RestaurantResource, TypeResource, ReviewResource
from tastypie.api import Api

api = Api(api_name='v1')
restaurant_resource = RestaurantResource()
type_resource = TypeResource()
review_resource = ReviewResource()
api.register(restaurant_resource)
api.register(type_resource)
api.register(review_resource)

urlpatterns = [
    path('', include(api.urls), name='index')
]

base/urls.py
from django.contrib import admin
from django.urls import path, include

from django.conf.urls.static import static
from django.conf import settings


urlpatterns = [
    path('admin/', admin.site.urls),
    # path('restaurant/', include('restaurant.urls')),
    path('', include('restaurant.urls')),
    path('accounts/', include('accounts.urls')),
    path('api/', include('api.urls'))
]
urlpatterns += static(settings.MEDIA_URL,
                      document_root=settings.MEDIA_ROOT)

restaurant/urls.py
from django.urls import path
from . import views
from django.conf.urls.static import static
from django.conf import settings
# from .views import single_restaurant

app_name = 'restaurant'
urlpatterns = [
    path('', views.index, name='index'),
    path('<int:rest_id>', views.single_restaurant, name='single_restaurant'),
    path('<int:rest_id>/create', views.createreview, name='createreview'),
    path('review/<int:review_id>', views.updatereview, name='updatereview'),
    path('review/<int:review_id>/delete',
         views.deletereview, name='deletereview'),
    # path('api/v1/restaurants/<int:restaurant_id>/reviews/',
    #      single_restaurant, name='restaurant-reviews'),
]
urlpatterns += static(settings.MEDIA_URL,
                      document_root=settings.MEDIA_ROOT)

restaurant/models.py
from django.db import models
from django.utils import timezone
from django.contrib.auth.models import User
from django.core.validators import MaxValueValidator, MinValueValidator

# Create your models here.


class Type(models.Model):
    name = models.CharField(max_length=100, db_index=True)
    # db_index=True selfedu
    created_at = models.DateTimeField(default=timezone.now)
    # created_at = models.DateTimeField(auto_now_add=True)

    def __str__(self):
        return self.name


class Restaurant(models.Model):
    title = models.CharField(max_length=200)
    place = models.CharField(max_length=200)
    note = models.CharField(max_length=900)
    image = models.ImageField(upload_to='restaurant/images/')
    # pri odstraneni Categorie, automaticky se odstrani vsechny restaurace v tomto Type
    # type = models.ForeignKey(Type, on_delete=models.CASCADE)
    type = models.ForeignKey(Type, on_delete=models.CASCADE)
    created_at = models.DateTimeField(default=timezone.now)

    def __str__(self):
        return self.title


class Review(models.Model):
    note = models.CharField(max_length=300)
    # the current datetime will be automatically filled in. This makes the field non-editable. Once the datetime is set, it is fixed
    user = models.ForeignKey(User, on_delete=models.CASCADE)
    restaurant = models.ForeignKey(
        Restaurant, related_name='reviews', on_delete=models.CASCADE)
    stars = models.IntegerField(default=5, choices=((i, i)
                                for i in range(1, 6)))
    expenses = models.IntegerField(
        default=5, validators=[MinValueValidator(1), MaxValueValidator(100000)])
    visit_date = models.DateField()
    created_at = models.DateTimeField(auto_now_add=True)

    def __str__(self):
        return self.note

restaurant/forms.py
from django.forms import ModelForm, Textarea, IntegerField
from .models import Review


class ReviewForm(ModelForm):
    def __init__(self, *args, **kwargs):
        super(ModelForm, self).__init__(*args, **kwargs)
        # set for each form field a class attribute to use a Bootstrap class.
        self.fields['note'].widget.attrs.update({'class': 'form-control'})
        # set for each form field a class attribute to use a Bootstrap class.
        self.fields['stars'].widget.attrs.update({'class': 'form-control'})
        self.fields['expenses'].widget.attrs.update({'class': 'form-control'})
        self.fields['visit_date'].widget.attrs.update(
            {'class': 'form-control'})
        self.fields['visit_date'].help_text = "YYYY-MM-DD"

    class Meta:
        """
        A class inside a class! 
        Specify which model the form is for and the fields we want in the form.

        More in documentation: 
        https://docs.djangoproject.com/en/4.2/topics/forms/modelforms/
        """
        model = Review
        # the only fields that the user has to fill are these
        fields = ['note', 'expenses', 'visit_date', 'stars']
        labels = {
            'stars': ('Stars'),
            'note': ('Text'),
            'expenses': ('Expenses, $'),
            'visit_date': ('Date of visit')
        }
        widgets = {
            'note': Textarea(attrs={'rows': 5}),
            # 'stars': IntegerField(attrs={'rows': 1}),

        }

restaurant/views.py
from django.shortcuts import render, get_object_or_404, redirect
from django.http import HttpResponse, Http404
from .models import Restaurant, Review
from .forms import ReviewForm
from django.contrib.auth.decorators import login_required
from django.db.models import Avg, Count, F, Func, IntegerField


# Create your views here.


def index(request):
    # return HttpResponse("Hello from the Restaurant app")
    searchTerm = request.GET.get('searchRestaurant')
    if searchTerm:
        restaurants = Restaurant.objects.filter(title__icontains=searchTerm)
    else:
        restaurants = Restaurant.objects.all()

    # Number of comments,                  без all
    # posts = restaurants.annotate(num_comments=Count('reviews')).all()
    # Average rating based on reviews
    # stars = Restaurant.objects.annotate(avg_rating=Func(
    #     Avg('reviews__stars'), function='ROUND', output_field=IntegerField()))
    restaurants = restaurants.annotate(num_comments=Count('reviews'), avg_rating=Func(
        Avg('reviews__stars'), function='ROUND', output_field=IntegerField()))
    # restaurants = Restaurant.objects.all()

    # return HttpResponse(''.join([str(rest) + '<br>' for rest in restaurants]))
    # return HttpResponse(restaurants)
    # return render(request=request, template_name='restaurant/restaurants.html', context={'restaurants': restaurants})
    # , 'posts': posts, 'stars': stars})
    return render(request, 'restaurant/restaurants.html', {'restaurants': restaurants, 'searchTerm': searchTerm})


# def single_restaurant(request, rest_id):
    # restaurant = Restaurant.objects.get(pk=rest_id)
    # return render(request, 'restaurant/single_restaurant.html', {'restaurant': restaurant})

    # Option 1
    # try:
    #     restaurant = Restaurant.objects.get(pk=rest_id)
    #     return render(request, 'restaurant/single_restaurant.html', {'restaurant': restaurant})
    # except Restaurant.DoesNotExist:
    #     raise Http404()
    #   # Option 2
    # restaurant = get_object_or_404(Restaurant, pk=rest_id)
    # reviews = Review.objects.filter(restaurant=restaurant)
    # return render(request, 'restaurant/single_restaurant.html', {'restaurant': restaurant, 'reviews': reviews})


def single_restaurant(request, rest_id):
    restaurant = get_object_or_404(Restaurant, pk=rest_id)
    reviews = Review.objects.filter(restaurant=restaurant)

    # Calculate the number of reviews and average rating
    num_reviews = reviews.count()
    avg_rating = reviews.aggregate(avg_rating=Func(
        Avg('stars'), function='ROUND', output_field=IntegerField()))

    return render(request, 'restaurant/single_restaurant.html', {
        'restaurant': restaurant,
        'reviews': reviews,
        'num_reviews': num_reviews,
        'avg_rating': avg_rating['avg_rating'] if avg_rating['avg_rating'] is not None else "No ratings yet"
    })


@login_required
def createreview(request, rest_id):
    restaurant = get_object_or_404(Restaurant, pk=rest_id)
    if request.method == 'GET':
        return render(request, 'restaurant/createreview.html', {'form': ReviewForm(), 'restaurant': restaurant})
    else:
        try:
            form = ReviewForm(request.POST)
            # We create and save a new review object from the form's values but do not yet put it into the
            # database (commit=False) because we want to specify the user and movie relationships for the review.
            newReview = form.save(commit=False)
            newReview.user = request.user
            newReview.restaurant = restaurant

            newReview.save()
            return redirect('restaurant:single_restaurant', newReview.restaurant.id)
        except ValueError:
            return render(request, 'restaurant/createreview.html', {'form': ReviewForm(), 'error': 'bad data passed in'})


@login_required
def updatereview(request, review_id):
    # supply the logged-in user to ensure that other users can't access the review – for example,
    # if they manually enter the URL path in the browser. Only the user who created this review can update/delete it.
    review = get_object_or_404(Review, pk=review_id, user=request.user)
    if request.method == 'GET':
        form = ReviewForm(instance=review)
        # render ReviewForm we used previously in creating a review, but this time, we pass the review object into the form so that the form's fields will be populated with the object's values, ready for the user to edit. Saves us time!
        return render(request, 'restaurant/updatereview.html', {'review': review, 'form': form})
    else:
        try:
            form = ReviewForm(request.POST, instance=review)
            form.save()
            return redirect('restaurant:single_restaurant', review.restaurant.id)
        except ValueError:
            return render(request, 'restaurant/updatereview.html', {'review': review, 'form': form, 'error': 'Bad data in form'})


@login_required
def deletereview(request, review_id):
    review = get_object_or_404(Review, pk=review_id, user=request.user)
    review.delete()
    return redirect('restaurant:single_restaurant', review.restaurant.id)

templates/restaurant/createreview.html
{% extends 'base.html' %}

{% block title %}{{restaurant.title}}{% endblock %}

{% block content %}
<div class="card mb-3">
    <div class="row g-0">
        <div>
            <div class="card-body">
                <h5 class="card-title">Add Review for {{ restaurant.title }}</h5>
                {% if error %}
                <div class="alert alert-danger mt-3" role="alert">
                    {{ error }}
                </div>
                {% endif %}
                <p class="card-text">
                <form method="POST">
                    {% csrf_token %}
                    {{ form.as_p }}
                    <button type="submit" class="btn btn-primary">Add Review</button>
                </form>
                </p>
            </div>
        </div>
    </div>
</div>
{% endblock content %}

templates/restaurant/restaurants.html
{% extends 'base.html' %}

{% block title %}All restaurants guide{% endblock %}

{% block content %}
<h1 class="my-5 text-center">Reviews</h1>
{% if not user.is_authenticated %}
    <h5 class="my-5 text-center">If you would like to leave a comment, please Sign Up or Log In</h5>
{% endif %}


{% comment %} S E A R C H   F O R M {% endcomment %}
<div class="container">
    <form action="">
        <div class="mb-3" style="width:35rem">
            <label class="form-label">Search for Restaurant:</label>
            <input type="text" name="searchRestaurant" class="form-control" />
        </div>
        <button type="submit" class="btn btn-primary text-white">Search</button>
    </form>
    {% if searchTerm %}
        Searching for {{ searchTerm }}
    {% endif %}
 </div>


{% comment %} T A B L E {% endcomment %}
<table class="table mt-5 table-bordered table-striped table-hover">
    <thead class="table-dark">
        <tr>
            <th>Title</th>
            <th>Photo</th>
            <th>Place</th>
            <th>Type</th>
            <th>Number of reviews</th>
            {% comment %} <th>Average Rating</th> {% endcomment %}
            <th></th>
        </tr>
    </thead>
    <tbody>
        {% for rest in restaurants %}
        <tr>
            <td>
                <h4 class='ms-2'>
                    <a href={% url "restaurant:single_restaurant" rest.id %} class="text-decoration-none">{{rest.title}}</a>
                        <br>
                    {% if rest.avg_rating is not None %}
                        {% with ''|center:rest.avg_rating as stars %}
                            {% for _ in stars %}
                                <img src="../../static/images/small_star.jpg" alt="Star">
                            {% endfor %}
                        {% endwith %}
                    {% else %}
                    <span class="text-secondary fs-5">No ratings yet</span>
                        
                    {% endif %}
                </a></h4>
                
            </td>

            <td style="width: 19.5rem;"><img class="card-img-top" style="height: 10rem; width: 18rem; overflow: hidden;" src="{{ rest.image.url }}" alt="photo"></td>
            <td style="width: 25rem;">{{rest.place}}</td>
            <td>{{rest.type}}</td>
            <td>{{ rest.num_comments }}</td>           
            <td><a class="btn btn-primary text-white px-4" href={% url "restaurant:single_restaurant" rest.id%}>Look</a></td>
        </tr>
        {% endfor %}
    </tbody>
</table>




{% comment %} C A R D S {% endcomment %}
<div class="d-flex justify-content-between gy-2 pb-5 mt-5">
    <div class="row row-cols-1 row-cols-md-2 row-cols-lg-3 row-cols-xl-4">
        {% for rest in restaurants %}
        <div v-for="rest in restaurants" class="col mb-2">
            <div class="blog card h-150 bg-light border rounded" style="width: 19.5rem; height: 33rem;">
                <img class="card-img-top" style="height: 13rem;" src="{{ rest.image.url }}" alt="photo">
                <div class="card-body" style="height: 16rem; overflow: hidden;">
                    <h5 class="card-title fw-bold ms-2"><a class="" href={% url "restaurant:single_restaurant" rest.id %}>{{ rest.title }}</a></h5>
                    
                    <p class="card-text ms-2">
                        {% if rest.avg_rating is not None %}
                            {% with ''|center:rest.avg_rating as stars %}
                                {% for _ in stars %}
                                    <img src="../../static/images/small_star.jpg" alt="Star">
                                {% endfor %}
                            {% endwith %}
                        {% else %}
                            No ratings yet
                        {% endif %}
                    </p>
                    <p class="card-text ms-2">{{ rest.place }}</p>
                    <p class="card-text ms-2">{{ rest.type }}</p>
                    <p class="card-text ms-2">Reviews: {{ rest.num_comments }}</p>
                    {% comment %} <p class="card-text ms-2">Avg rating: {{ rest.avg_rating|default:"No ratings yet" }}</p> {% endcomment %}
                    <p class="card-text ms-2">{{ rest.note }}</p>
                </div>
                <div class="card-footer mb-3 border-0 bg-light">
                    <a class="btn btn-primary px-4 ms-2"
                    href={% url "restaurant:single_restaurant" rest.id %}>Read more ...</a>
                    
                </div>
            </div>
        </div>        
        {% endfor %}
    </div>
</div>
{% endblock %}

templates/restaurant/single_restaurant.html
{% extends 'base.html' %}

{% load static %}

{% block title %}{{restaurant.title}}{% endblock %}

{% block content %}
<div class="container mb-5">
    <h1 class="mt-5 mb-5">{{restaurant.title}}</h1>
    <div class="row">
        <div class="col-sm-8">
            <p>{{ restaurant.note }}</p>
        </div>
        <div class="col-sm-4 text-center">
            <img class="card-img-top" style="height: 15rem;" src="{{ restaurant.image.url }}" alt="photo">
        </div>
    </div>
    
    
    <div class="row mt-3">
        <div class="col-sm-2">
            <p><b>Address:</b></p>
        </div>
        <div class="col-sm-4">
            {{restaurant.place}}
        </div>
    </div>
    <div class="row mt-1">
        <div class="col-sm-2">
            <p><b>Type:</b></p>
        </div>
        <div class="col-sm-4">
            {{restaurant.type}}
        </div>
    </div>
    <div class="row mt-1">
        <div class="col-sm-2">
            <p><b>Number of Reviews:</b></p>
        </div>
        <div class="col-sm-4">
            {{num_reviews}}
        </div>
    </div>
    <div class="row mt-1">
        <div class="col-sm-2">
            <p><b>Average Rating:</b></p>
        </div>
        <div class="col-sm-4">
            {{avg_rating}}
        </div>
    </div>
   

    <h3 class="mt-5">Reviews</h3>
    {% if user.is_authenticated %}
    <!-- Users who are not logged in will not see the Add Review link. -->
        <a href="{% url 'restaurant:createreview' restaurant.id %}" class="btn btn-primary px-4 py-1my-3">Add Review</a>
    {% endif %}

    {% if user.is_authenticated and not reviews %}
        <h5>There is no any review jet.  Leave your feedback and be the first.</h5>
    {% elif not reviews %}
        <h5>There is no any review yet.</h5>
    {% endif %}


    <ul class="list-group">
        {% for review in reviews %}
        <li class="list-group-item pb-3 pt-3">
            <h5 class="card-title">
                Review by <span class="text-success">{{ review.user.username }}</span>
            </h5>
            <h6 class="card-subtitle mb-2 text-muted">
                {{ review.created_at }}
            </h6>
            <p class="card-text">{{ review.note }}</p>
            <p class="card-text">Expenses, $: {{ review.expenses }}</p>
            <p class="card-text">Visit date: {{ review.visit_date }}</p>
            

            {% with ''|center:review.stars as stars %}
            {% for _ in stars %}
                <img src="../../static/images/star.png" alt="Star">
            {% endfor %}                
            {% endwith %}

            <br>
            

            {% if user.is_authenticated and user == review.user %}
                <a class="btn btn-primary px-4 py-1 me-2 mt-3" href="{% url 'restaurant:updatereview' review.id %}">Update</a>
                <a class="btn btn-danger px-4 py-1 mt-3" href="{% url 'restaurant:deletereview' review.id %}">Delete</a>
            {% endif %}
        </li>
        {% endfor %}
    </ul>

</div>

{% endblock %}

templates/restaurant/updatereview.html
{% extends 'base.html' %}

{% load static %}

{% block title %}{{restaurant.title}}{% endblock %}
{% block content %}
<div class="container mb-5">
    <div class="card my-5">
        <div class="row g-0">
            <div>
                <div class="card-body">
                    <h5 class="card-title">
                        Update Review for <span class="text-success"> {{ review.restaurant.title }}</span>
                    </h5>
                    {% if error %}
                    <div class="alert alert-danger mt-3" role="alert">
                        {{ error }}
                    </div>
                    {% endif %}
                    <p class="card-text">
                    <form method="POST">
                        {% csrf_token %}
                        {{ form.as_p }}
                        <button type="submit" class="btn btn-primary px-4 py-1me-2">
                            Update Review
                        </button>
                    </form>
                    </p>
                </div>
            </div>
        </div>
    </div>
</div>
{% endblock content %}